import { builtinModules } from "node:module";
import { copyFile, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";

const projectRoot = fileURLToPath(new URL(".", import.meta.url));
const outDir = resolve(projectRoot, "dist");
const bundledFileName = "main.js";
const bundledStyleFileName = "styles.css";
const externalPackages = new Set([
	"obsidian",
	"electron",
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
]);
const externalPrefixes = ["@codemirror/", "@lezer/"];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

function isExternal(id: string): boolean {
	return externalPackages.has(id) || externalPrefixes.some((prefix) => id.startsWith(prefix));
}

function copyBundleToPluginRoot() {
	return {
		name: "copy-bundle-to-plugin-root",
		closeBundle: async () => {
			await Promise.all([
				copyFile(resolve(outDir, bundledFileName), resolve(projectRoot, bundledFileName)),
				copyFile(
					resolve(outDir, bundledStyleFileName),
					resolve(projectRoot, bundledStyleFileName),
				),
			]);
			await rm(outDir, { force: true, recursive: true });
		},
	};
}

export default defineConfig(({ mode }) => {
	const isProduction = mode === "production";

	return {
		build: {
			copyPublicDir: false,
			lib: {
				entry: resolve(projectRoot, "src/obsidian/main.ts"),
				formats: ["cjs"],
				cssFileName: "styles",
				fileName: () => bundledFileName,
			},
			cssCodeSplit: false,
			cssMinify: false,
			minify: isProduction,
			outDir,
			rolldownOptions: {
				external: isExternal,
				output: {
					banner,
					entryFileNames: bundledFileName,
					exports: "named",
				},
			},
			sourcemap: isProduction ? false : "inline",
			target: "es2018",
		},
		define: {
			"process.env.NODE_ENV": JSON.stringify(isProduction ? "production" : "development"),
		},
		esbuild: {
			jsx: "automatic",
		},
		plugins: [copyBundleToPluginRoot()],
	};
});
