// =============================================================================
// Backward compatibility layer for src/ui/components
// Re-exports all components from new primitives and views locations
// =============================================================================

export {
	FlashcardButton,
	Button,
	type ButtonVariant,
	type ButtonPreset,
	type ButtonSize,
	type FlashcardButtonProps,
	type ButtonProps,
	FlashcardInput,
	Input,
	FlashcardTextarea,
	Textarea,
	type FlashcardInputProps,
	type InputProps,
	type FlashcardTextareaProps,
	type TextareaProps,
	FlashcardCheckbox,
	Checkbox,
	type FlashcardCheckboxProps,
	type CheckboxProps,
	FlashcardSlider,
	Slider,
	type FlashcardSliderProps,
	type SliderProps,
	FlashcardSelect,
	Select,
	type FlashcardSelectProps,
	type SelectProps,
	FlashcardMenu,
	Menu,
	type FlashcardMenuItem,
	type MenuItem,
	type FlashcardMenuProps,
	type MenuProps,
	FlashcardHeader,
	Header,
	type FlashcardHeaderProps,
	type HeaderProps,
	type FlashcardHeaderStat,
	type FlashcardHeaderStatTone,
	Modal,
	ModalProvider,
	ModalSurface,
	type ModalId,
	ConfirmDialog,
	type ConfirmDialogProps,
	type ConfirmDialogTone,
	SessionTimer,
	formatElapsedTime,
	SessionToolbar,
	type SessionToolbarProps,
	SetupSelector,
	SetupControlGroup,
	type SetupSelectorOption,
	type SetupControlGroupProps,
	MarkdownContent,
	renderMarkdownWithLifecycle,
	type MarkdownRendererFn,
	PronounceableMarkdown,
	type PronounceableMarkdownProps,
	PronunciationButton,
	type PronunciationButtonProps,
	type PronunciationButtonRuntimeProps,
} from "../primitives";

export {
	DeckList,
	CardView,
	CardEditorModal,
	type CardEditorDeckOption,
	type CardEditorMode,
	type CardEditorSavePayload,
	PracticeSetup,
	PracticeView,
	PracticeSummary,
	WordListView,
	StudySetup,
	StatsView,
	SpellingSetup,
	SpellingView,
	SpellingSummary,
	DeckSettingsModal,
	type DeckSettingsModalProps,
} from "../views";

export { I18nProvider, useI18n } from "../context/I18nContext";
export { useLatestRef, useWindowKeyDown } from "../hooks/hooks";
export { FlashcardApp } from "../FlashcardApp";
