#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const gitDir = path.resolve(process.cwd(), ".git");
const hooksDir = path.resolve(gitDir, "hooks");

if (!fs.existsSync(gitDir)) {
	console.log("\x1b[33m[WARN]\x1b[0m 未检测到 .git 目录，跳过 Git hooks 安装。");
	process.exit(0);
}

if (!fs.existsSync(hooksDir)) {
	fs.mkdirSync(hooksDir, { recursive: true });
}

// 1. commit-msg hook
const commitMsgHookPath = path.resolve(hooksDir, "commit-msg");
const commitMsgHookContent = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.mjs
node scripts/verify-commit-msg.mjs "$1"
`;

fs.writeFileSync(commitMsgHookPath, commitMsgHookContent, { mode: 0o755 });
console.log("\x1b[32m✔\x1b[0m commit-msg hook 已配置");

// 2. pre-commit hook
const preCommitHookPath = path.resolve(hooksDir, "pre-commit");
const preCommitHookContent = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.mjs

echo "\x1b[36m🔍 运行提交前代码检查 (format & lint)...\x1b[0m"

# 1. 格式检查
npm run format:check
if [ $? -ne 0 ]; then
  echo "\n\x1b[31m❌ 代码格式检查未通过！请先运行 'npm run format' 进行自动格式化后重试。\x1b[0m\n"
  exit 1
fi

# 2. 类型与 Lint 检查
npm run lint
if [ $? -ne 0 ]; then
  echo "\n\x1b[31m❌ 代码 Lint / 类型检查未通过！请修复上述错误后重试。\x1b[0m\n"
  exit 1
fi

echo "\x1b[32m✔ 提交前代码质量检查通过\x1b[0m"
`;

fs.writeFileSync(preCommitHookPath, preCommitHookContent, { mode: 0o755 });
console.log("\x1b[32m✔\x1b[0m pre-commit hook 已配置");

console.log("\x1b[32m✨ Git hooks 安装完成！\x1b[0m");
